// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionDemo.Persistence.src.Context.Main;

#nullable disable

namespace OnionDemo.Persistence.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231204132234_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnionDemo.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PK_CATEGORY");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CREATED");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TX_DESCRIPTION");

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit")
                        .HasColumnName("SW_DEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("TX_NAME")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("CATEGORY", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1f04949-fb5f-4286-9f2a-2f8b0c06e7de"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Kategori 2 açıklaması.",
                            IsDel = false,
                            Name = "Kategori 2"
                        },
                        new
                        {
                            Id = new Guid("0de8e949-21f7-45e7-9d4e-536b30072d35"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Kategori 5 açıklaması.",
                            IsDel = false,
                            Name = "Kategori 5"
                        },
                        new
                        {
                            Id = new Guid("3d60e3e9-da05-47a7-9cc5-6fa19995e781"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Kategori 3 açıklaması.",
                            IsDel = false,
                            Name = "Kategori 3"
                        },
                        new
                        {
                            Id = new Guid("4a3221b5-2da5-44b0-aac4-78b6728a3717"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Kategori 4 açıklaması.",
                            IsDel = false,
                            Name = "Kategori 4"
                        },
                        new
                        {
                            Id = new Guid("e4f41d7d-6d47-4b24-9a4f-91e7d7741f28"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Kategori 1 açıklaması.",
                            IsDel = false,
                            Name = "Kategori 1"
                        });
                });

            modelBuilder.Entity("OnionDemo.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PK_PRODUCT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FK_CATEGORY_ID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CREATED");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TX_DESCRIPTION");

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit")
                        .HasColumnName("SW_DEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("TX_NAME")
                        .IsFixedLength();

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("NO_PRICE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a696f00d-3a2e-48bf-88bb-1f3f416570fb"),
                            CategoryId = new Guid("3d60e3e9-da05-47a7-9cc5-6fa19995e781"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 0, DateTimeKind.Unspecified),
                            Description = "Ürün 7 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 7",
                            Price = 80
                        },
                        new
                        {
                            Id = new Guid("63b179cc-5c4e-44f2-9b9a-49a74416bb80"),
                            CategoryId = new Guid("b1f04949-fb5f-4286-9f2a-2f8b0c06e7de"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 4 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 4",
                            Price = 120
                        },
                        new
                        {
                            Id = new Guid("5f7fe0f9-07b7-45d3-a3e9-4e39de2e4423"),
                            CategoryId = new Guid("4a3221b5-2da5-44b0-aac4-78b6728a3717"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 10 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 10",
                            Price = 75
                        },
                        new
                        {
                            Id = new Guid("d6661d2f-8b78-4c24-9cb3-578c62ab35a1"),
                            CategoryId = new Guid("0de8e949-21f7-45e7-9d4e-536b30072d35"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 13 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 13",
                            Price = 95
                        },
                        new
                        {
                            Id = new Guid("b542bc9f-ec79-4a2e-9180-7a4a97c74a72"),
                            CategoryId = new Guid("e4f41d7d-6d47-4b24-9a4f-91e7d7741f28"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 3 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 3",
                            Price = 200
                        },
                        new
                        {
                            Id = new Guid("2efdd11b-b2c5-470e-8a7b-960e4711483d"),
                            CategoryId = new Guid("3d60e3e9-da05-47a7-9cc5-6fa19995e781"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 9 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 9",
                            Price = 140
                        },
                        new
                        {
                            Id = new Guid("a394e328-2b8f-4d4a-8f56-a41e7c0a3c46"),
                            CategoryId = new Guid("b1f04949-fb5f-4286-9f2a-2f8b0c06e7de"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 5 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 5",
                            Price = 180
                        },
                        new
                        {
                            Id = new Guid("e824abfd-ca71-4e09-9eac-a9d590ef42d2"),
                            CategoryId = new Guid("0de8e949-21f7-45e7-9d4e-536b30072d35"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 15 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 15",
                            Price = 155
                        },
                        new
                        {
                            Id = new Guid("df34cc80-b98e-4af3-8eaa-b7a76aae66fc"),
                            CategoryId = new Guid("4a3221b5-2da5-44b0-aac4-78b6728a3717"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 11 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 11",
                            Price = 105
                        },
                        new
                        {
                            Id = new Guid("e0160c83-a45d-49da-a1ac-c8b88cdb84fb"),
                            CategoryId = new Guid("0de8e949-21f7-45e7-9d4e-536b30072d35"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 0, DateTimeKind.Unspecified),
                            Description = "Ürün 2 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 2",
                            Price = 1500
                        },
                        new
                        {
                            Id = new Guid("607a4e57-4ae4-4770-9f63-cdeb1d7e9f52"),
                            CategoryId = new Guid("4a3221b5-2da5-44b0-aac4-78b6728a3717"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 12 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 12",
                            Price = 135
                        },
                        new
                        {
                            Id = new Guid("85c4848c-adfd-4e47-8afb-ce572a1b0a8a"),
                            CategoryId = new Guid("3d60e3e9-da05-47a7-9cc5-6fa19995e781"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 8 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 8",
                            Price = 110
                        },
                        new
                        {
                            Id = new Guid("5f9668b0-f70f-45ee-a9a6-cf6d845d1e25"),
                            CategoryId = new Guid("e4f41d7d-6d47-4b24-9a4f-91e7d7741f28"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 0, DateTimeKind.Unspecified),
                            Description = "Ürün 1 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 1",
                            Price = 100
                        },
                        new
                        {
                            Id = new Guid("8e6b2ec8-c5e3-47ac-8e4d-f02a00c82b2b"),
                            CategoryId = new Guid("0de8e949-21f7-45e7-9d4e-536b30072d35"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 14 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 14",
                            Price = 125
                        },
                        new
                        {
                            Id = new Guid("ec6cec30-ac14-4b61-a1f4-f0e7c5e69d72"),
                            CategoryId = new Guid("b1f04949-fb5f-4286-9f2a-2f8b0c06e7de"),
                            Created = new DateTime(2023, 11, 3, 22, 5, 26, 790, DateTimeKind.Unspecified),
                            Description = "Ürün 6 açıklaması.",
                            IsDel = false,
                            Name = "Ürün 6",
                            Price = 220
                        });
                });

            modelBuilder.Entity("OnionDemo.Domain.Product", b =>
                {
                    b.HasOne("OnionDemo.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
